// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiServer.Data;

#nullable disable

namespace WebApiServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240128175055_WebApiServer2")]
    partial class WebApiServer2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedData.Models.KeySetting", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KeySettingString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("KeySettings");
                });

            modelBuilder.Entity("SharedData.Models.PlayerSetting", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlayerSettingString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("PlayerSettings");
                });

            modelBuilder.Entity("SharedData.Models.SoundSetting", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Bgm")
                        .HasColumnType("real");

                    b.Property<float>("Effects")
                        .HasColumnType("real");

                    b.Property<float>("Master")
                        .HasColumnType("real");

                    b.HasKey("UserId");

                    b.ToTable("SoundSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
